### ISSUE TITLE
Add footer with reference to data.gov.sg and terms of use

### ISSUE THREAD

**Issue by caalberts** [caalberts/hdb-flats#38]

**Comment by yongjun21** [comment]
Do take note of this: [https://data.gov.sg/terms](https://data.gov.sg/terms)

**Comment by caalberts** [comment]
- [x] clearly indicate that any analysis or transformation of data are made by you and shall not be attributed to the Singapore Government or its Statutory Boards
- [x] clearly state in your applications or websites containing the datasets: "The datasets provided by the Singapore Government and its Statutory Boards via Data.gov.sg are governed by the Terms of Use available at https://data.gov.sg/terms. To the fullest extent permitted by law, the Singapore Government and its Statutory Boards are not liable for any damage or loss of any kind caused directly or indirectly by the use of the datasets or any derived analyses or applications."
- [ ] register with Data.gov.sg here if you intend to use the datasets to develop applications or for other commercial purposes; and

**Comment by caalberts** [comment]
@yongjun21 How about this in the footer to comply with the terms? In this case the footer cannot be fixed to the bottom of viewport

```
Data retrieved December 28, 2015 from data.gov.sg. Data analysis and representation are independent of the Singapore Government or its Statutory Boards.
The datasets provided by the Singapore Government and its Statutory Boards via Data.gov.sg are governed by the Terms of Use available at https://data.gov.sg/terms. To the fullest extent permitted by law, the Singapore Government and its Statutory Boards are not liable for any damage or loss of any kind caused directly or indirectly by the use of the datasets or any derived analyses or applications.
```
